"""Constantes metier officielles de SALMOSPHARM."""

from __future__ import annotations


APP_NAME = "SALMOSPHARM 133"
APP_VERSION = "1.0.0"
BACKUP_FORMAT_VERSION = 1

ROLE_GERANT = "GERANT"
ROLE_VENDEUR = "VENDEUR"
ROLES_VALIDES = (ROLE_GERANT, ROLE_VENDEUR)

DEVISE_UNIQUE = "CDF"
MODE_PAIEMENT_UNIQUE = "ESPECES"

STATUT_VENTE_VALIDEE = "VALIDEE"

TYPE_MOUVEMENT_ENTREE = "ENTREE"
TYPE_MOUVEMENT_SORTIE = "SORTIE"
TYPE_MOUVEMENT_AJUSTEMENT = "AJUSTEMENT"
TYPE_MOUVEMENT_PERTE = "PERTE"
TYPE_MOUVEMENT_EXPIRATION = "EXPIRATION"
TYPES_MOUVEMENT_STOCK = (
    TYPE_MOUVEMENT_ENTREE,
    TYPE_MOUVEMENT_SORTIE,
    TYPE_MOUVEMENT_AJUSTEMENT,
    TYPE_MOUVEMENT_PERTE,
    TYPE_MOUVEMENT_EXPIRATION,
)

TYPE_ALERTE_STOCK_FAIBLE = "STOCK_FAIBLE"
TYPE_ALERTE_EXPIRATION_PROCHE = "EXPIRATION_PROCHE"
TYPE_ALERTE_PRODUIT_EXPIRE = "PRODUIT_EXPIRE"
TYPES_ALERTES = (
    TYPE_ALERTE_STOCK_FAIBLE,
    TYPE_ALERTE_EXPIRATION_PROCHE,
    TYPE_ALERTE_PRODUIT_EXPIRE,
)

LARGEUR_TICKET_58 = 58
LARGEUR_TICKET_80 = 80
LARGEURS_TICKET = (LARGEUR_TICKET_58, LARGEUR_TICKET_80)

ACTION_CONNEXION_REUSSIE = "CONNEXION_REUSSIE"
ACTION_CONNEXION_ECHOUEE = "CONNEXION_ECHOUEE"
ACTION_COMPTE_GERANT_CREE = "COMPTE_GERANT_CREE"
ACTION_CODE_RECUPERATION_GENERE = "CODE_RECUPERATION_GENERE"
ACTION_MOT_DE_PASSE_REINITIALISE = "MOT_DE_PASSE_REINITIALISE"
ACTION_UTILISATEUR_CREE = "UTILISATEUR_CREE"
ACTION_UTILISATEUR_MODIFIE = "UTILISATEUR_MODIFIE"
ACTION_UTILISATEUR_DESACTIVE = "UTILISATEUR_DESACTIVE"
ACTION_UTILISATEUR_REACTIVE = "UTILISATEUR_REACTIVE"
ACTION_PRODUIT_CREE = "PRODUIT_CREE"
ACTION_PRODUIT_MODIFIE = "PRODUIT_MODIFIE"
ACTION_PRODUIT_DESACTIVE = "PRODUIT_DESACTIVE"
ACTION_STOCK_ENTREE = "STOCK_ENTREE"
ACTION_STOCK_AJUSTE = "STOCK_AJUSTE"
ACTION_VENTE_VALIDEE = "VENTE_VALIDEE"
ACTION_FACTURE_IMPRIMEE = "FACTURE_IMPRIMEE"
ACTION_FACTURE_REIMPRIMEE = "FACTURE_REIMPRIMEE"
ACTION_BACKUP_EXPORTE = "BACKUP_EXPORTE"
ACTION_BACKUP_IMPORTE = "BACKUP_IMPORTE"
ACTION_SAUVEGARDE_AUTO_CREEE = "SAUVEGARDE_AUTO_CREEE"
ACTION_PARAMETRES_MODIFIES = "PARAMETRES_MODIFIES"
ACTION_ERREUR_IMPRESSION = "ERREUR_IMPRESSION"
ACTION_ERREUR_IMPORT_BACKUP = "ERREUR_IMPORT_BACKUP"

ACTIONS_JOURNAL = (
    ACTION_CONNEXION_REUSSIE,
    ACTION_CONNEXION_ECHOUEE,
    ACTION_COMPTE_GERANT_CREE,
    ACTION_CODE_RECUPERATION_GENERE,
    ACTION_MOT_DE_PASSE_REINITIALISE,
    ACTION_UTILISATEUR_CREE,
    ACTION_UTILISATEUR_MODIFIE,
    ACTION_UTILISATEUR_DESACTIVE,
    ACTION_UTILISATEUR_REACTIVE,
    ACTION_PRODUIT_CREE,
    ACTION_PRODUIT_MODIFIE,
    ACTION_PRODUIT_DESACTIVE,
    ACTION_STOCK_ENTREE,
    ACTION_STOCK_AJUSTE,
    ACTION_VENTE_VALIDEE,
    ACTION_FACTURE_IMPRIMEE,
    ACTION_FACTURE_REIMPRIMEE,
    ACTION_BACKUP_EXPORTE,
    ACTION_BACKUP_IMPORTE,
    ACTION_SAUVEGARDE_AUTO_CREEE,
    ACTION_PARAMETRES_MODIFIES,
    ACTION_ERREUR_IMPRESSION,
    ACTION_ERREUR_IMPORT_BACKUP,
)
